#!/usr/local/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# source "$SCRIPT_DIR/.venv/bin/activate"

DIST="$SCRIPT_DIR/dist"
echo "[PUBLISH] cleaning $DIST"
rm -r $DIST
mkdir "$DIST"

echo "[PUBLISH] running setup.py"
python3 setup.py sdist

echo "[PUBLISH] publishing with twine"
twine upload dist/*